export const DUMMY_DATA = [
  {
    id: 1,
    name: 'Toronto',
    country: 'CA',
    sunny: true,
    date: 'Fri,19 February, 19:25',
    currentTemp: '+4',
    wind: '30 m/s',
    humidity: '20%',
    pressure: '650Pa',
  },
  {
    id: 2,
    name: 'Calgary',
    country: 'CA',
    sunny: true,
    date: 'Fri,19 February, 19:25',
    currentTemp: '+2',
    wind: '30 m/s',
    humidity: '20%',
    pressure: '650Pa',
  },
  {
    id: 3,
    name: 'Moscow',
    country: 'CA',
    sunny: true,
    date: 'Fri,19 February, 19:25',
    currentTemp: '+10',
    wind: '30 m/s',
    humidity: '20%',
    pressure: '650Pa',
  },
  {
    id: 4,
    name: 'New-York',
    country: 'CA',
    sunny: true,
    date: 'Fri,19 February, 19:25',
    currentTemp: '+9',
    wind: '30 m/s',
    humidity: '20%',
    pressure: '650Pa',
  },
  {
    id: 5,
    name: 'Athens',
    country: 'CA',
    sunny: true,
    date: 'Fri,19 February, 19:25',
    currentTemp: '+20',
    wind: '30 m/s',
    humidity: '20%',
    pressure: '650Pa',
  },
  {
    id: 6,
    name: 'Istanbul',
    country: 'CA',
    sunny: true,
    date: 'Fri,19 February, 19:25',
    currentTemp: '+25',
    wind: '30 m/s',
    humidity: '20%',
    pressure: '650Pa',
  },
  {
    id: 7,
    name: 'Toronto',
    country: 'CA',
    sunny: true,
    date: 'Fri,19 February, 19:25',
    currentTemp: '+4',
    wind: '30 m/s',
    humidity: '20%',
    pressure: '650Pa',
  },
  {
    id: 8,
    name: 'Toronto',
    country: 'CA',
    sunny: true,
    date: 'Fri,19 February, 19:25',
    currentTemp: '+4',
    wind: '30 m/s',
    humidity: '20%',
    pressure: '650Pa',
  },
  {
    id: 9,
    name: 'Toronto',
    country: 'CA',
    sunny: true,
    date: 'Fri,19 February, 19:25',
    currentTemp: '+4',
    wind: '30 m/s',
    humidity: '20%',
    pressure: '650Pa',
  },
  {
    id: 10,
    name: 'Toronto',
    country: 'CA',
    sunny: true,
    date: 'Fri,19 February, 19:25',
    currentTemp: '+4',
    wind: '30 m/s',
    humidity: '20%',
    pressure: '650Pa',
  },
  {
    id: 11,
    name: 'Toronto',
    country: 'CA',
    sunny: true,
    date: 'Fri,19 February, 19:25',
    currentTemp: '+4',
    wind: '30 m/s',
    humidity: '20%',
    pressure: '650Pa',
  },
  {
    id: 12,
    name: 'Toronto',
    country: 'CA',
    sunny: true,
    date: 'Fri,19 February, 19:25',
    currentTemp: '+4',
    wind: '30 m/s',
    humidity: '20%',
    pressure: '650Pa',
  },
  {
    id: 13,
    name: 'Toronto',
    country: 'CA',
    sunny: true,
    date: 'Fri,19 February, 19:25',
    currentTemp: '+4',
    wind: '30 m/s',
    humidity: '20%',
    pressure: '650Pa',
  },
  {
    id: 14,
    name: 'Toronto',
    country: 'CA',
    sunny: true,
    date: 'Fri,19 February, 19:25',
    currentTemp: '+4',
    wind: '30 m/s',
    humidity: '20%',
    pressure: '650Pa',
  },
];

export type City = {
  id: number;
  name: string;
  country: string;
  sunny: boolean;
  date: string;
  currentTemp: string;
  wind: string;
  humidity: string;
  pressure: string;
};
